name: "Deployment pipeline"

on:
  push:
    branches:
      - master

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-18.04
    steps:
      - name: "Run actions/checkout@v2"
        uses: actions/checkout@v2
      - name: "ls"
        run: ls -al
      - name: "Run actions/setup-node@v1"
        uses: actions/setup-node@v1
        with:
          node_version: "12.x"
      - name: "npm install"
        run: npm install
      - name: "npm run eslint"
        run: npm run eslint
      - name: "build"
        run: npm run build
      - name: "jest (frontend) test"
        run: "npm run test"
      - name: "e2e tests"
        uses: cypress.io/github-action@v2
        with:
          command: npm run test:e2e
          start: npm run start-prod
          wait-on: http://localhost:5000



